### PR TITLE
Loosen up two rules

### PR DESCRIPTION
**Pull request by zacanger**
## Change Type

* [ ] Feature
* [x] Chore
* [ ] Bug Fix

## Change Level

* [ ] major
* [ ] minor
* [x] patch

## Further Information (screenshots, etc)

After spending a bit of time trying to get rid of all warnings, I think these two rules might be a little too restrictive. Any thoughts?

### CODE REVIEW

**Comment by zacanger** [comment]
I won't merge as soon as someone approves, this time.

**Comment by TomPridham** [comment]
are there examples of code that is failing on `complexity: 10`? 20 seems like a ridiculous amount of paths

**Comment by zacanger** [comment]
Any function with more than 10 possible branches.

```javascript
const buildUser = (info) => ({
  name: info.name || '',
  address1: info.address1 || '',
  address2: info.address2 || '',
  city: info.city || '',
  state: info.state || '',
  zip: info.zip || '',
  roles: info.roles || [],
  features: info.features || [],
  email: info.email || '',
  isEmployee: (info.roles || []).includes('employee'),
  isAdmin: (info.roles || []).includes('admin'),
})
```

already has 11.

**Comment by zacanger** [comment]
Another good example is Redux Form/React Final Form validation.

```
const validate = (values) => {
  const errors = {}
  if (!values.firstName) errors.firstName = 'Please enter your given name.'
  // etc., etc., etc.
  return errors
}
```

That can easily hit over 10 possible branches.

**Comment by TomPridham** [comment]
huh. i never thought about those counting as different paths, but that makes sense. Is there someway to make either of those examples better? or should we just disable it for functions like that?

**Comment by zacanger** [comment]
The first one could be broken up, or have some default object things are set to. The second one can possibly be done with a reduce, as long as you know all your possible values beforehand and don't have too many different validation error messages. It's awkward, though.

**Comment by jhelst** [comment]
Looks good to me. We have some connect files that probably hit these warnings.

**Pull request merged**
